# Travis-CI Build for libgit2sharp
# see travis-ci.org for details

language: shell

os:
- osx
osx_image: xcode8

env:
 global:

before_install:
 - date -u
 - uname -a
 - env | sort

# Build libgit2, LibGit2Sharp and run the tests
script:
 - xcodebuild -version

# Notify of build changes
notifications:
 email:
  - nowarry@gmail.com
